spring.application.name=GestionIcfes

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionicfes?useSSL=false&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=tamao
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type = TRACE
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
